# NumPy (Numerical Python)

Numpy es un paquete de Python para computación científica. Permite una generación y un manejo de datos extremadamente rápidos.

## ```array```

Este paquete tiene su propia estructura de datos llamada ```array```. Los arreglos son similares a las listas pero tienen muchos más métodos integrados,lo que facilita la operación con los datos almacenados.

In [1]:
#Debemos importar el paquete
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9,10] 
#Podemos crear un array a partir de una lista
array = np.array(lista)

Podemos pensar en los arreglos como **matrices y vectores:** Los vectores son arreglos de una sola fila y las matrices son arreglos de vectores.

In [3]:
array1 = np.array(['Este','es','un','vector'])
array2 = np.array(['Este','es','otro','vector'])
array3 = np.array(['Este','es','otro','vector más'])
matriz = np.array([array1,array2,array3])

print('{0},{1},{2}\n'.format(array1,array2,array3))
print('Esto es una matriz: \n{0}'.format(matriz))

['Este' 'es' 'un' 'vector'],['Este' 'es' 'otro' 'vector'],['Este' 'es' 'otro' 'vector más']

Esto es una matriz: 
[['Este' 'es' 'un' 'vector']
 ['Este' 'es' 'otro' 'vector']
 ['Este' 'es' 'otro' 'vector más']]


## Métodos para crear arreglos

In [4]:
#Crea un arreglo de números enteros entre los argumentos 1 y 2
#Podemos agregar el paso en el tercer argumento.
array1 = np.arange(-10,10,2)

#Crea un arreglo de n ceros donde n es el argumento
array2 = np.zeros(5)

#Crea un arreglo de n unos donde n es el argumento
array3 = np.ones(5)

#para tener un arreglo de n numeros x 
#podemos multiplicar el arreglo anterior por x
array4  = 2*array3

#Crea un arreglo numérico espaciados uniformemente
#El primer argumento es el inicio del intervalo
#El segundo argumento es el final del intervalo
#El ultimo argumento es el número de datos que queremos
#------ (Se distribuirán uniformemente) ----------------
array5 = np.linspace(0,100,10)

#Crea un arreglo identidad de nxn donde n es el argumento
array6 = np.eye(5)

In [5]:
print('Arreglo de números entre -10 y 10 con paso 2:\n{0}\n\n\
Arreglo de 5 ceros:\n{1}\n\nArreglo de 5 unos:\n{2}\n\n\
Arreglo de 5 dos:\n{3}\n\nArreglo distribuido uniformemente:\n{4}\n\n\
matriz identidad de 5x5:\n{5}'.format(array1,array2,array3,array4,array5,array6))

Arreglo de números entre -10 y 10 con paso 2:
[-10  -8  -6  -4  -2   0   2   4   6   8]

Arreglo de 5 ceros:
[0. 0. 0. 0. 0.]

Arreglo de 5 unos:
[1. 1. 1. 1. 1.]

Arreglo de 5 dos:
[2. 2. 2. 2. 2.]

Arreglo distribuido uniformemente:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]

matriz identidad de 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Métodos con números aleatorios

In [6]:
#genera un array de mxn numeros aleatorios entre 0 y 1
#donde m es el número de filas
#donde n es el número de columnas
a = np.random.rand(1,5)

#Si queremos un array de n números aleatorios entre 0 y 10
b = 10*a

#Genera una array de números enteros aleatorios en el intervalo
# [Primer argumento, Segundo argumento)
# De n elementos donde n es el tercer argumento

arrayrand = np.random.randint(-10,10,5)

In [7]:
print('Este es un arreglo de números aleatorios entre 0 y 1:\n{0}\n\n\
Este es un arreglo de números aleatorios entre 0 y 10:\n{1}\n\n\
Este es un arreglo de números enteros aleatorios en el intervalo \
[-10,10) de 5 elementos:\n{2}'.format(a,b,arrayrand))

Este es un arreglo de números aleatorios entre 0 y 1:
[[0.60058095 0.06487148 0.91108736 0.68672106 0.92694477]]

Este es un arreglo de números aleatorios entre 0 y 10:
[[6.00580946 0.6487148  9.11087362 6.86721062 9.26944767]]

Este es un arreglo de números enteros aleatorios en el intervalo [-10,10) de 5 elementos:
[ 4 -3 -2  9 -8]


## Remodelar arrays

In [15]:
array = np.random.rand(8,3)

#Te dice las dimensiones del array
array.shape 

#Cambia las dimensiones del array
#DEBE TENER LA MISMA CANTIDAD DE ELEMENTOS
array = array.reshape(6,4)

## Máximos y mínimos

In [18]:
print(array.max()) #retorna el valor maximo
print(array.argmax()) #retorna el índice del valor maximo
print(array.min()) #retorna el valor mínimo
print(array.argmin()) #retorna el índice del valor mínimo

0.9860718952543279
21
0.0018075178281897752
6


# Funciones $f(x)$

* $\large e^x \rightarrow$ ```np.exp(x)```


* $\large \sin{x} \rightarrow$ ```np.sin(x)```


* $\large \cos{x} \rightarrow$ ```np.cos(x)```


* $\large \log{x} \rightarrow$ ```np.log(x)```


* $\sqrt{x} \rightarrow$ ``` np.sqrt(x)```

Para redondear un arreglo de números a $\text{n}$ cifras significativas usamos el método ```np.round(x,n)```